config/routes.rb
Rails.application.routes.draw do
  devise_for :employees
  devise_for :companies
  devise_for :users

  root to: "site#users_home"

  get '/users', to: 'site#users_home'
  get '/companies', to: 'site#companies_home'
  get '/employees', to: 'site#employees_home'
  get '/api_sinparun/nike', to: 'site#activity_user_nike'
  get '/api_sinparun/runtastic', to: 'site#activity_user_runtastic'

  get '/users/sync_account/nike', to: 'users#sync_account_nike'
  get '/users/sync_account/runtastic', to: 'users#sync_account_runtastic'
  get '/users/check_id_activity', to: 'users#check_id_activity'
  get '/users/branches_map/:company_id', to: 'users#branches_map', as: 'users_branches_map'

  get '/branches_map/:company_id', to: 'companies#branches_map', as: 'branches_map'

  get '/employees/validate', to: 'employees#validate'
  get '/validate_response', to: 'employees#validate_response'

  get '/users/rewards', to: 'rewards#all_rewards'

  get '/search_coupon', to: 'coupons#search_coupon'
  get '/users/rewards_map', to: 'coupons#rewards_map'
  get '/users/edit_coupon/:id', to: 'coupons#edit_coupon', as: 'edit_coupon'

  resources :users do
    resources :races, :coupons
  end

  resources :companies do
    resources :branches, :rewards do
      resources :rewards, :employees
    end
  end

  resources :employees do
    resources :coupons
  end

end

app/models/reward.rb
class Reward < ActiveRecord::Base
  belongs_to :user
  belongs_to :company
  belongs_to :branch
  has_many :coupons

  validates :name, presence: true, length: { maximum: 15}, format: {with: /\A[a-zA-ZÑñ0-9\ ]+\z/}
  validates :kms_cost, :available_units, :description, :valid_from, :valid_through, :image, presence: true

  has_attached_file :image, styles: { medium: "300x300>", small: "200x200!", xsmall: "150x150>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  filterrific(
    default_filter_params: { sorted_by: 'created_at_desc' },
    available_filters: [:sorted_by, :search_query])

  scope :sorted_by, lambda { |sort_option|
  direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
  case sort_option.to_s
  when /^created_at_/

    order("rewards.created_at #{ direction }")
  else
    raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
  end
}

  scope :with_city, lambda { |city|
    where(city: [*city])
  }

  scope :search_query, lambda { |query|
  return nil  if query.blank?
  return nil if query.class == Fixnum

  terms = query.downcase.split(/\s+/)

  terms = terms.map { |e|
    (e.gsub('*', '%') + '%').gsub(/%+/, '%')
  }

  num_or_conds = 2
  where(
    terms.map { |term|
      "(LOWER(rewards.name) LIKE ? OR LOWER(rewards.name) LIKE ?)"
    }.join(' AND '),
    *terms.map { |e| [e] * num_or_conds }.flatten
  )
}

def self.options_for_sorted_by
    [
      ['Name (a-z)', 'name_asc'],
      ['Registration date (newest first)', 'created_at_desc'],
      ['Registration date (oldest first)', 'created_at_asc'],
    ]
  end

end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController

  def index
    @company = Company.find(params[:company_id])
    @rewards = @company.rewards
  end

  def reset_filterrific
    session[:filterrific_rewards] = nil
    redirect_to action: :index
  end

  def all_rewards
    @allRewards = Reward.all
    @filterrific = initialize_filterrific(
      Reward,
      params[:filterrific]
    ) or return
    @all_rewards = @filterrific.find.page(params[:page])
  end

  def new
    @company = Company.find(params[:company_id])
    @reward = Reward.new
  end

  def create
    @company = Company.find(params[:company_id])
    @reward = Reward.new reward_params
    @reward.company_id = params[:company_id]
    if @reward.save
      flash[:notice] = "Reward created succesfully"
      redirect_to company_rewards_path(current_company.id,params[:id])
    else
      flash[:alert] = "ALERT Reward not created"
      render 'new'
    end
  end

  def show
    @company = Company.find(params[:company_id])
    @reward = Reward.find(params[:id])
  end

  def destroy
    @reward = Reward.find(params[:id])
    @reward.destroy
    redirect_to company_rewards_path(current_company.id,params[:id])
  end

  private

  def reward_params
   params.require(:reward).permit(:name, :kms_cost, :description, :valid_from, :valid_through, :available_units, :image)
  end

end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/rewards/_form.html.erb
<% if @reward.errors.any? %>
  <ul class="notification">
    <% @reward.errors.full_messages.each do |error| %>
     <li><%= error %> </li>
    <% end %>
  </ul>
<% end%>


<%= form_for [current_company,@branch,@reward] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, size: 10, required:'' %>
  <br>
  <%= f.label :kms_cost %>
  <%= f.number_field :kms_cost, size: 10, within: 1...1000, required:''%>
  <br>
  <%= f.label :description %>
  <%= f.text_field :description, size: 10, required:'' %>
  <br>
  <%= f.label :valid_from %>
  <%= f.date_field :valid_from, size: 10, class: "valid_from", value: Time.now.to_date, min: Time.now.to_date, required:'' %>
  <br>
  <%= f.label :valid_through %>
  <%= f.date_field :valid_through, size: 10, class: "valid_through", value: Time.now.to_date+30.days, min: Time.now.to_date, required:'' %>
  <br>
  <%= f.label :available_units %>
  <%= f.number_field :available_units, size: 10, within: 1...100, required:'' %>
  <br>
  <%= f.label :image %>
  <%= f.file_field :image, size: 10, required:'' %>
  <br>

  <%= f.submit 'Save' %>

<% end %>
<br>
<a href="<%= company_branch_path(current_company.id, @company.id) %>">Back to Branch</a>

app/views/rewards/_list.html.erb
<div id="filterrific_results">

  <table>
    <span class="table_titles">
      <th>Company</th>
      <th>Reward</th>
      <th>Kms cost</th>
    </span>

    <% @all_rewards.each do |reward| %>
      <tr>
        <td id="table_results" ><%= reward.company.name %></td>
        <td><%= link_to(reward.name, users_branches_map_path(reward.company.id)) %></td>
        <td><%= reward.kms_cost %></td>
      </tr>
    <% end %>
  </table>
</div>

<%= paginate rewards %>

app/views/rewards/_search.html.erb
<%= form_for_filterrific @filterrific do |f| %>
  <div>
    Search
    <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
    <%= f.text_field(
      :search_query,
      class: 'filterrific-periodically-observed'
    ) %>
  </div>
  <div>
    Country
    <%= f.select(
      :with_country_id,
      @filterrific.select_options[:with_country_id],
      { include_blank: '- Any -' }
    ) %>
  </div>
  <div>
    Registered after
    <%= f.text_field(:with_created_at_gte, class: 'js-datepicker') %>
  </div>
  <div>
    Sorted by
    <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by]) %>
  </div>
  <div>
    <%= link_to(
      'Reset filters',
      reset_filterrific_url,
    ) %>
  </div>
  <%# add an automated spinner to your form when the list is refreshed %>
  <%= render_filterrific_spinner %>
<% end %>

<%= render(
  partial: 'students/list',
  locals: { students: @students }
) %>

app/views/rewards/all_rewards.html.erb
<h2 class="title is-2 sync_label">Get your rewards</h2>
<br>
<div class="error">
  <%= flash_message %>
  <% if flash_message == "Sorry don't have enough kms !"%>

  <% end %>
</div>


<div class="row">
  <div class="col s12">
    <%= form_for_filterrific @filterrific do |f| %>
      <div>
        <div class="input-field col s12">
          <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
          <%= f.text_field(:search_query, class: 'filterrific-periodically-observed') %>
          <label class="active" for="first_name2"><i class="material-icons">search</i> by name</label>
        </div>
        <div>
         <%= link_to('Reset filters',reset_filterrific_url) %>
       </div>
         <% if @all_rewards.length != 0%>
       <div class="col s12" style="text-align: center, ">
         <%= render(partial: 'rewards/list', locals: { rewards: @all_rewards }) %>
       </div>
       <% end %>

      </div>
    <% end %>
  </div>
</div>

<div class="row">
 <div class="col s12">
   <% @allRewards.each_with_index do |reward, index| %>
   <% if reward.valid_from < Time.now %>
     <!-- card -->
      <div class="card">
       <div class="card-image waves-effect waves-block waves-light">
         <div class="img_show_reward activator" >
           <%= image_tag reward.image.url(:medium) %>
         </div>

       </div>
       <div class="card-content">
         <span class="card-title activator grey-text text-darken-4">
           <b><%= "#{reward.kms_cost}" %> kms</b> - <%= "#{reward.name}" %>
           <i class="material-icons right glyphicon glyphicon-sunglasses"></i></span>
         <p><a href="<%= edit_coupon_path(reward.id) %>">Get</a></p>
       </div>
       <div class="card-reveal">
         <span class="card-title grey-text text-darken-4"><%= "#{reward.name}" %><i class="material-icons right glyphicon glyphicon glyphicon glyphicon-remove-circle"></i></span>
         <p>
           <ul>
             <li><strong>Description: </strong> <%= "#{reward.description}" %></li>
             <li><strong>Kms cost: </strong> <%= "#{reward.kms_cost}" %></li>
             <li><strong>Locations: </strong> <a href='/users/branches_map/<%= "#{reward.company_id}"  %>'><%= "#{reward.company.name}" %></a></li>
             <li><strong>Valid from: </strong> <%= "#{reward.valid_from.to_date}" %></li>
             <li><strong>Valid through: </strong> <%= "#{reward.valid_through.to_date}" %></li>
             <li><strong>Available units: </strong> <%= "#{reward.available_units}" %></li>
             <br>
             <a href="<%= edit_coupon_path(reward.id) %>">Get</a>
           </ul>
         </p>
       </div>
      </div>
    <!-- /card -->
  <% end %>
 <% end %>
 </div>
</div>

<br>

<a href="<%= user_path(current_user)%>">Back to Profile</a>

app/views/rewards/index.html.erb
<h2 class="title is-2 sync_label"><%= @company.name%>'s rewards </h2>
<br>


<div class="row">
  <div class="col-md-12">
    <h5> Active Rewards</h5>
    <% @rewards.each_with_index do |reward, index| %>
      <% if reward.valid_through > Time.now %>
    <ul class="collapsible" data-collapsible="accordion">
      <li>
        <div class="collapsible-header"><i class="material-icons">grade</i><%= reward.name %></div>
        <div class="collapsible-body">
          <table class="highlight centered">
              <thead>
                <tr>
                  <th data-field="name">Description</th>
                  <th data-field="name">Kms cost</th>
                  <th data-field="name">Valid from</th>
                  <th data-field="name">Valid through</th>
                  <th data-field="name">Available units</th>
                  <th data-field="name">Reserved units</th>
                  <th data-field="name">Charged units</th>
                  <th data-field="price">Action</th>
                </tr>
              </thead>

              <tbody>
                <tr>
                  <td><%= "#{reward.description}" %></td>
                  <td><%= "#{reward.kms_cost}" %></td>
                  <td><%= "#{reward.valid_from.to_date}" %></td>
                  <td><%= "#{reward.valid_through.to_date}" %></td>
                  <td><%= "#{reward.available_units}" %></td>
                  <td><%= "#{reward.reserved_units}" %></td>
                  <td><%= "#{reward.charged_units}" %></td>
                  <td><a href="<%= company_reward_path(current_company.id, reward.id) %>">Show</a> / <a data-method="DELETE" href="<%= company_reward_path(current_company.id, reward.id) %>">Delete</a></td>
                </tr>

              </tbody>
            </table>
        </div>
      </li>
    </ul>
    <% end %>
  <% end %>
  </div>

  <div class="col-md-12">
    <h5> Expired Rewards</h5>
    <% @rewards.each_with_index do |reward, index| %>
      <% if reward.valid_through < Time.now %>
    <ul class="collapsible" data-collapsible="accordion">
      <li>
        <div class="collapsible-header"><i class="material-icons">grade</i><%= reward.name %></div>
        <div class="collapsible-body">
          <table class="highlight centered">
              <thead>
                <tr>
                  <th data-field="name">Description</th>
                  <th data-field="name">Kms cost</th>
                  <th data-field="name">Valid from</th>
                  <th data-field="name">Valid through</th>
                  <th data-field="name">Available units</th>
                  <th data-field="name">Reserved units</th>
                  <th data-field="name">Charged units</th>
                  <th data-field="price">Action</th>
                </tr>
              </thead>

              <tbody>
                <tr>
                  <td><%= "#{reward.description}" %></td>
                  <td><%= "#{reward.kms_cost}" %></td>
                  <td><%= "#{reward.valid_from.to_date}" %></td>
                  <td><%= "#{reward.valid_through.to_date}" %></td>
                  <td><%= "#{reward.available_units}" %></td>
                  <td><%= "#{reward.reserved_units}" %></td>
                  <td><%= "#{reward.charged_units}" %></td>
                  <td><a href="<%= company_reward_path(current_company.id, reward.id) %>">Show</a> / <a data-method="DELETE" href="<%= company_reward_path(current_company.id, reward.id) %>">Delete</a></td>
                </tr>

              </tbody>
            </table>
        </div>
      </li>
    </ul>
    <% end %>
  <% end %>
  </div>

</div>

<br>
<a href="<%= new_company_reward_path(current_company.id) %>" class="row btn" >Add Reward</a>
<br>
<a href="<%= company_path(current_company.id) %>">Back to Company Profile</a>

app/views/rewards/new.html.erb
<h2 class="title is-2 sync_label">Create new Reward</h2>
<br>

<%= render "form" %>

app/views/rewards/show.html.erb
<h2 class="title is-2 sync_label"><%= @reward.name%></h2>
<br>

<div class="row statistics2 font_2">
  <section class="col-md-6">
    <ul>
      <li> <strong>Name:</strong> <%= "#{@reward.name}" %></li>
      <li> <strong>Kms cost:</strong> <%= "#{@reward.kms_cost}" %></li>
      <li> <strong>Description:</strong> <%= "#{@reward.description}" %></li>
      <li> <strong>Valid from:</strong> <%= "#{@reward.valid_from.to_date}" %></li>
      <li> <strong>Valid through:</strong> <%= "#{@reward.valid_through.to_date}" %></li>
      <li> <strong>Available units:</strong> <%= "#{@reward.available_units}" %></li>
      <li> <strong>Reserved units:</strong> <%= "#{@reward.reserved_units}" %></li>
      <li> <strong>Charged units:</strong> <%= "#{@reward.charged_units}" %></li>
      <br>
    </ul>
  </section>

  <section class="col-md-6">
    <div class="img_show_reward" >
      <%= image_tag @reward.image.url(:medium)  %>
    </div>
  </section>
</div>
<br>
<a href="<%= company_rewards_path(current_company.id) %>">My Rewards</a>
<br>
<a href="<%= company_path(current_company.id)%>">Back to Company profile</a>