config/routes.rb
Rails.application.routes.draw do
  devise_for :employees
  devise_for :companies
  devise_for :users

  root to: "site#users_home"

  get '/users', to: 'site#users_home'
  get '/companies', to: 'site#companies_home'
  get '/employees', to: 'site#employees_home'
  get '/api_sinparun/nike', to: 'site#activity_user_nike'
  get '/api_sinparun/runtastic', to: 'site#activity_user_runtastic'

  get '/users/sync_account/nike', to: 'users#sync_account_nike'
  get '/users/sync_account/runtastic', to: 'users#sync_account_runtastic'
  get '/users/check_id_activity', to: 'users#check_id_activity'
  get '/users/branches_map/:company_id', to: 'users#branches_map', as: 'users_branches_map'

  get '/branches_map/:company_id', to: 'companies#branches_map', as: 'branches_map'

  get '/employees/validate', to: 'employees#validate'
  get '/validate_response', to: 'employees#validate_response'

  get '/users/rewards', to: 'rewards#all_rewards'

  get '/search_coupon', to: 'coupons#search_coupon'
  get '/users/rewards_map', to: 'coupons#rewards_map'
  get '/users/edit_coupon/:id', to: 'coupons#edit_coupon', as: 'edit_coupon'

  resources :users do
    resources :races, :coupons
  end

  resources :companies do
    resources :branches, :rewards do
      resources :rewards, :employees
    end
  end

  resources :employees do
    resources :coupons
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :coupons
  has_many :kms

  validates :name, presence: true, length: { maximum: 250 }
  validates :email, uniqueness: true
  validates :password, presence: true, format: {with: /\A[a-zA-ZÑñ0-9\ ]+\z/}
  # validates :password, length: { minumum: 8 }
  # validates_each :password do |record, attr, value|
  #   record.errors.add(attr, 'must start with upper case') if value =~ /\A[[:lower:]]/
  #   end
  # /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])\w{8,}$/

 has_attached_file :avatar, styles: {
   medium: "300x300>",
   small: "200x200!",
   xsmall: "150x150>",
   thumb: "100x100>" },
   default_url: "/images/avatar1.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def self.new_runner_nike(current_user,params)
    current_user_kms = Km.create(sinparun_kms:0,
     total_kms:0,
     nike_last_total_kms:params[:totalDistance].to_i,
     level: 1, races: 1, user_id:current_user.id)
  end

  def self.new_nike_account(current_user,params)
    kms_accounts = current_user.kms[0]
    kms_accounts.nike_last_total_kms = params[:totalDistance].to_i
    kms_accounts.save
    kms_accounts
  end

  def self.update_runner_nike(current_user,params)
    kms_accounts = current_user.kms[0]
    if params[:totalDistance].to_i > kms_accounts.nike_last_total_kms
      nike_new_kms = params[:totalDistance].to_i - kms_accounts.nike_last_total_kms
      kms_accounts.sinparun_kms = kms_accounts.sinparun_kms + nike_new_kms
      kms_accounts.total_kms = kms_accounts.total_kms + nike_new_kms
      kms_accounts.nike_last_total_kms = params[:totalDistance].to_i
      kms = kms_accounts.total_kms
      level = kms/100 == 0 ? 1 : (kms/100 + 1)
      kms_accounts.level = level
      kms_accounts.races = kms_accounts.races + 1
      kms_accounts.save
      kms_accounts
      kms_accounts
   else
    kms_accounts
   end
  end

  def self.new_runner_runtastic(current_user,params)
    current_user_kms = Km.create(sinparun_kms:0,
     total_kms:0,
     runtastic_last_total_kms:params[:totalDistance].to_i,
     level: 1, races: 1, user_id:current_user.id)
  end

  def self.new_runtastic_account(current_user,params)
    kms_accounts = current_user.kms[0]
    kms_accounts.runtastic_last_total_kms = params[:totalDistance].to_i
    kms_accounts.save
    kms_accounts
  end

  def self.update_runner_runtastic(current_user,params)
    kms_accounts = current_user.kms[0]
    if params[:totalDistance].to_i > kms_accounts.runtastic_last_total_kms
      runtastic_new_kms = params[:totalDistance].to_i - kms_accounts.runtastic_last_total_kms
      kms_accounts.sinparun_kms = kms_accounts.sinparun_kms + runtastic_new_kms
      kms_accounts.total_kms = kms_accounts.total_kms + runtastic_new_kms
      kms_accounts.runtastic_last_total_kms = params[:totalDistance].to_i
      kms = kms_accounts.total_kms
      level = kms/100 == 0 ? 1 : (kms/100 + 1)
      kms_accounts.level = level
      kms_accounts.races = kms_accounts.races + 1
      kms_accounts.save
      kms_accounts
      kms_accounts
   else
    kms_accounts
   end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "users"
  before_action :authenticate_user!, except: :update

  def profile
   @user = current_user
   render 'users/profile'
  end

  def show
     @allRewards = Reward.all
     @coupons = current_user.coupons
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes user_params
      redirect_to action: :profile
    else
      render "edit"
    end

  end

  def branches_map
    @company = Company.find(params[:company_id])
    @branches = @company.branches
  end

 def sync_account_nike
   if current_user.kms.length == 0
     set_new_runner = User.new_runner_nike(current_user, params)
     render json: set_new_runner_nike, status: 201
   elsif current_user.kms[0].nike_last_total_kms == 0
     set_new_nike_account = User.new_nike_account(current_user, params)
     render json: set_new_nike_account, status: 201
   else
    update_runner_account = User.update_runner_nike(current_user, params)
     render json:update_runner_account, status: 201
   end
 end

 def sync_account_runtastic
   if current_user.kms.length == 0
     set_new_runner = User.new_runner_runtastic(current_user, params)
     render json: set_new_runner, status: 201
   elsif current_user.kms[0].runtastic_last_total_kms == 0
     set_new_runtastic_account = User.new_runtastic_account(current_user, params)
     render json: set_new_runtastic_account, status: 201
   else
    update_runner_account = User.update_runner_runtastic(current_user, params)
     render json:update_runner_account, status: 201
   end
 end

 private

 def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation)
 end

end

app/helpers/users_helper.rb
module UsersHelper

  def controller_name
    UsersController.name
  end
end

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <ul class="notification is-danger">
    <button class="delete"></button>
    <% @user.errors.full_messages.each do |error| %>
     <li><%= error %> </li>
    <% end %>
  </ul>
<% end%>


<%= form_for [@user] do |f| %>
  <div class="field">
  <%= f.label :name %>
  <%= f.text_field :name, size: 10, required:'' %>
  </div>
  <br>
  <div class="field">
  <%= f.label :email %>
  <%= f.text_field :email, size: 10, required:'' %>
  </div>
  <br>
  <div class="field">
  <%= f.label :password %>
  <%= f.password_field :password, size: 10, required:'' %>
  </div>
  <br>
  <div class="field">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, size: 10, required:'' %>
  </div>
  <br>
  <div class="field">
  <%= f.label :avatar %>
  <%= f.file_field :avatar %>
  </div>
  <br>

  <%= f.submit 'Save' %>

<% end %>

app/views/users/branches_map.html.erb
<h2 class="title is-2 sync_label">This rewards near your location</h2>
<br>
<div class="">
 <div class="">
   <div id="rewards_map2"></div>
 </div>
</div>
<br>
<span class="js-user-name" data-user-name='<%= "#{current_user.name}" %>'></span>
<ul>
  <% @branches.each_with_index do |branch, index| %>
    <li><span class="js-rewards-name" data-rewards-name='<%= "#{branch.name}" %>'></span></li>
    <li><span class="js-rewards-lat" data-rewards-lat='<%= "#{branch.latitude}" %>'></span></li>
    <li><span class="js-rewards-long" data-rewards-long='<%= "#{branch.longitude}" %>'></span></li>
    <ul>
      <% branch.company.rewards.each_with_index do |reward, index| %>
        <li><span class="js-branch-reward" data-branch-rewards='<%= "#{reward.name}" %>'></span></li>
        <br>
      <% end %>
    </ul>
    <br>
  <% end %>
</ul>

<a href="<%= users_rewards_path %>">Back to Rewards</a>

app/views/users/edit.html.erb
<h2 class="session_title sync_label">Edit <%= @user.name %></h2>

<%= render "form" %>

<br>
<%= link_to("Back to Profile", user_path(current_user.id)) %>

app/views/users/show.html.erb
<section class="user_background">

  <div class="user_info counter_label row z-depth-2">
    <div class="valign-wrapper">
      <div class="col-sm-3 valign">
          <div class="profile_img materialboxed" width="650">
          <%= image_tag current_user.avatar.url(:medium) %>
          </div>
          <h6 class="message"></h6>
      </div>
      <div class="col-sm-3 valign">
        <h5 class="kms_counter"><%= current_user.kms.length == 0 ? 0 : current_user.kms[0].sinparun_kms %></h5>
        <h5>Kms Sinpa</h5>
      </div>
      <div class="col-sm-3 valign">
        <h5 class="total_kms_counter"><%= current_user.kms.length == 0 ? 0 : current_user.kms[0].total_kms %></h5>
        <h5>Total kms</h5>
      </div>
      <div class="col-sm-3 valign">
        <h5 class="level_counter"><%= current_user.kms.length == 0 ? 0 : current_user.kms[0].level %></h5>
        <h5>Level</h5>
      </div>
    </div>
  </div>

  <div class="row section3 hoverable">
    <h5 class="sync_label">Syncronize your kms</h5>
    <br>
    <div class="col-sm-2">
      <button class="js-btn-nike sync_button waves-effect waves-light" type="button" name="button">
        <img src="/images/nike_logo.jpg" alt="" />
      </button>
    </div>
    <div class="col-sm-2">
      <button class="js-btn-runtastic sync_button waves-effect waves-light" type="button" name="button">
        <img src="/images/runtastic.png" alt="" />
      </button>
    </div>
    <div class="col-sm-2">
      <button class="sync_button tooltipped waves-effect waves-light" data-position="top" data-delay="50" data-tooltip="Coming soon" type="button" name="button">
        <img src="/images/endomondo.jpg" alt="" />
      </button>
    </div>
    <div class="col-sm-2">
      <button class="sync_button tooltipped waves-effect waves-light" data-position="top" data-delay="50" data-tooltip="Coming soon" type="button" name="button">
        <img src="/images/runkeeper_icon.png" alt="" />
      </button>
    </div>
    <div class="col-sm-2">
      <button class="sync_button tooltipped waves-effect waves-light" data-position="top" data-delay="50" data-tooltip="Coming soon" type="button" name="button">
        <img src="/images/sportstracker.png" alt="" />
      </button>
    </div>
    <div class="col-sm-2">
      <button class="sync_button tooltipped waves-effect waves-light" data-position="top" data-delay="50" data-tooltip="Coming soon" type="button" name="button">
        <img src="/images/tomtom.png" alt="" />
      </button>
    </div>
    <br>

  </div>

  <div class="row">
    <div class="col-sm-6 section2 hoverable">
      <div class="reserved_coupons">
          <h5 class="sync_label ">Reserved coupons</h5>
          <a class="" href="<%= user_coupons_path(current_user) %>" class="waves-effect waves-light">view all</a>
          <div class="coupon_list ">
            <br>
            <% @coupons.each_with_index do |coupon, index| %>
            <% if coupon.redeemed == "reserved" %>
              <div class="chip">
                <img class="valign" src="/images/<%= coupon.reward.image_file_name %>" alt="Contact Person">
                <%= coupon.reward.name %>
                - <a href="<%= user_coupon_path(current_user,coupon) %>"><%= coupon.code %></a>
              </div>
              <% end %>
              <br>
            <% end %>
          </div>
      </div>
    </div>

      <div class="col-sm-5 col-sm-offset-1 section1 hoverable">
        <h5 class="sync_label">Latest rewards</h5>
        <a href="<%= users_rewards_path(current_user) %>" class="waves-effect waves-light">View all</a>
        - <a href="<%= users_rewards_map_path(current_user) %>" class="btn-rewards_map">view in map</a>
        <br>
        <div class="">
         <div class="">
           <% @allRewards.each_with_index do |reward, index| %>
           <% if reward.valid_from < Time.now && index < 4 %>
             <!-- card -->
              <div class="card ">
               <div class="card-image waves-effect waves-block waves-light">
                 <div class="img_show_reward activator" >
                   <%= image_tag reward.image.url(:medium) %>
                 </div>

               </div>
               <div class="card-content">
                 <span class="card-title activator grey-text text-darken-4">
                   <b><%= "#{reward.kms_cost}" %> kms</b> - <%= "#{reward.name}" %>
                   <i class="material-icons right glyphicon glyphicon-sunglasses"></i></span>
                 <p><a href="<%= edit_coupon_path(reward.id) %>">Get</a></p>
               </div>
               <div class="card-reveal">
                 <span class="card-title grey-text text-darken-4"><%= "#{reward.name}" %><i class="material-icons right glyphicon glyphicon glyphicon glyphicon-remove-circle"></i></span>
                 <p>
                   <ul>
                     <li><strong>Description: </strong> <%= "#{reward.description}" %></li>
                     <li><strong>Kms cost: </strong> <%= "#{reward.kms_cost}" %></li>
                     <li><strong>Locations: </strong> <a href='/users/branches_map/<%= "#{reward.company_id}"  %>'><%= "#{reward.company.name}" %></a></li>
                     <li><strong>Valid from: </strong> <%= "#{reward.valid_from.to_date}" %></li>
                     <li><strong>Valid through: </strong> <%= "#{reward.valid_through.to_date}" %></li>
                     <li><strong>Available units: </strong> <%= "#{reward.available_units}" %></li>
                     <br>
                     <a href="<%= edit_coupon_path(reward.id) %>">Get</a>
                   </ul>
                 </p>
               </div>
              </div>
            <!-- /card -->
          <% end %>
         <% end %>
         </div>
        </div>
      </div>

  </div>

  <br>
    <b><a style="color: black" href="<%=edit_user_path(current_user.id)%>">Edit profile</a></b>

</section>