config/routes.rb
Rails.application.routes.draw do
  devise_for :employees
  devise_for :companies
  devise_for :users

  root to: "site#users_home"

  get '/users', to: 'site#users_home'
  get '/companies', to: 'site#companies_home'
  get '/employees', to: 'site#employees_home'
  get '/api_sinparun/nike', to: 'site#activity_user_nike'
  get '/api_sinparun/runtastic', to: 'site#activity_user_runtastic'

  get '/users/sync_account/nike', to: 'users#sync_account_nike'
  get '/users/sync_account/runtastic', to: 'users#sync_account_runtastic'
  get '/users/check_id_activity', to: 'users#check_id_activity'
  get '/users/branches_map/:company_id', to: 'users#branches_map', as: 'users_branches_map'

  get '/branches_map/:company_id', to: 'companies#branches_map', as: 'branches_map'

  get '/employees/validate', to: 'employees#validate'
  get '/validate_response', to: 'employees#validate_response'

  get '/users/rewards', to: 'rewards#all_rewards'

  get '/search_coupon', to: 'coupons#search_coupon'
  get '/users/rewards_map', to: 'coupons#rewards_map'
  get '/users/edit_coupon/:id', to: 'coupons#edit_coupon', as: 'edit_coupon'

  resources :users do
    resources :races, :coupons
  end

  resources :companies do
    resources :branches, :rewards do
      resources :rewards, :employees
    end
  end

  resources :employees do
    resources :coupons
  end

end

app/models/company.rb
class Company < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :rewards
   has_many :branches

   validates :name, :email, uniqueness: true, presence: true, length: { maximum: 250 }
   validates :password, presence: true

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  layout "companies"

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])

    if @company.update_attributes company_params
      redirect_to action: :index
    else
      render "edit"
    end
  end

  def show
    @company = Company.find(params[:id])
    @branches = @company.branches
    @rewards = @company.rewards
  end

  def branches_map
    @company = Company.find(params[:company_id])
    @branches = @company.branches
  end

  private

  def company_params
   params.require(:company).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<% if @company.errors.any? %>
  <ul class="notification is-danger">
    <button class="delete"></button>
    <% @company.errors.full_messages.each do |error| %>
     <li><%= error %> </li>
    <% end %>
  </ul>
<% end%>


<%= form_for [@company] do |f| %>
  <div class="field">
  <%= f.label :name %>
  <%= f.text_field :name, size: 10, required:'' %>
  </div>
  <br>
  <div class="field">
  <%= f.label :email %>
  <%= f.text_field :email, size: 10, required:'' %>
  </div>
  <br>
  <div class="field">
  <%= f.label :password %>
  <%= f.password_field :password, size: 10, required:'' %>
  </div>
  <br>
  <div class="field">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, size: 10, required:'' %>
  </div>
  <br>

  <%= f.submit 'Save' %>

<% end %>

app/views/companies/branches_map.html.erb
<h2 class="title_companies is-2 sync_label">Branches location</h2>
<br>
<div class="row">
 <div class="map_container col-md-12">
   <div id="branches_map"></div>
 </div>
</div>
<br>
<ul>
  <% @branches.each_with_index do |branch, index| %>
    <li><span class="js-branch-lat" data-branch-lat='<%= "#{branch.latitude}" %>'></span></li>
    <li><span class="js-branch-long" data-branch-long='<%= "#{branch.longitude}" %>'></span></li>
    <br>
  <% end %>
</ul>

<a href="<%= company_path(current_company.id)%>">Back to Company profile</a>

app/views/companies/edit.html.erb
<h2 class="session_title">Edit <%= @company.name %></h2>

<%= render "form" %>

<br>
<%= link_to("Back to Company", company_path(current_company.id)) %>

app/views/companies/show.html.erb
<section class="company_background">

<h2 class="title_companies sync_label"><%= current_company.name %> </h2>

<div class="row">
  <div class="col-md-7">
    <h5 class="title_companies">Rewards</h5>
    <span><a href="<%= new_company_reward_path(current_company.id) %>" class="">Add Reward</a></span>
    <% @rewards.each_with_index do |reward, index| %>
    <ul class="collapsible hoverable" data-collapsible="accordion">
      <li>
        <div class="collapsible-header"><i class="material-icons">grade</i><%= reward.name %></div>
        <div class="collapsible-body">
          <table class="highlight centered">
              <thead>
                <tr>
                    <th data-field="name">Description</th>
                    <th data-field="name">Status</th>
                    <th data-field="price">Action</th>
                </tr>
              </thead>

              <tbody>
                <tr>
                  <td class=""><%= "#{reward.description}" %></td>
                  <% if reward.valid_through < Time.now %>
                  <td>Expired</td>
                  <% else %>
                  <td>Active</td>
                  <% end %>
                  <td><a href="<%= company_reward_path(current_company.id, reward.id) %>">Show</a>
                    - <a data-method="DELETE" href="<%= company_reward_path(current_company.id, reward.id) %>">Delete</a></td>
                </tr>

              </tbody>
            </table>
        </div>
      </li>
    </ul>
  <% end %>
  </div>

  <div class="col-md-4 col-sm-offset-1">
    <h5 class="title_companies">Branches</h5>
    <span><a href="<%= new_company_branch_path(current_company.id) %>" class="">Add Branch</a></span>
    - <a href="<%= branches_map_path(current_company.id) %>" class="">view map</a>
    <% @branches.each_with_index do |branch, index| %>
    <ul class="collapsible hoverable" data-collapsible="accordion">
      <li>
        <div class="collapsible-header"><i class="material-icons">location_on</i><%= branch.name %></div>
        <div class="collapsible-body">
          <table class="highlight centered">
              <thead>
                <tr>

                    <th data-field="name">Address</th>
                    <th data-field="price">Action</th>
                </tr>
              </thead>

              <tbody>
                <tr>
                  <td class="title_boxes"><%= "#{branch.address}" %></td>
                  <td><a href="<%= company_branch_path(current_company.id, branch.id) %>">Show</a>
                    - <a data-method="DELETE" href="<%= company_branch_path(current_company.id, branch.id) %>">Delete</a></td>
                </tr>
              </tbody>
            </table>
          </div>
        </li>
      </ul>
    <% end %>
  </div>
</div>

    <br>
    <a class="btn waves-effect waves-light" href="<%= edit_company_path(current_company.id) %>">Edit Company</a>


</section>